spring.application.name=centavos
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.omxrynqpjlyvmiizmgzd
spring.datasource.password=VascoCampeao1998#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
server.port=8081